/*Copyright (c) 2011, 2022, Oracle and/or its affiliates.  All rights reserved.*/
/*MF:S MF:L*/
try{(function(r,m){function y(){var a={},n=0,c=!1,h="MFPA_"+m.floor(m.random()*m.pow(10,12)),l=.1>m.random();this.__d=function(d){if(l&&d&&"object"===typeof d)for(var b in d)d.hasOwnProperty(b)&&(a[b]=d[b])};this.sp=function(d){if(!l||!d||c&&d.LOAD)return!1;d.LOAD?(n=a.e=0,c=!0):d.FALLBACK_LOADED?(a.tc=1,a.e=9,n=1):d.AD_FOUND&&(a.tc=1,a.id=1,a.e=9,n=2);a.g=n;a.cm=10;var b;d="";for(b in a)if(a.hasOwnProperty(b)){var e=encodeURIComponent(a[b]);d+="&"+b+"="+e}b=d.slice(1);d=b;e=new r;e=[e.getFullYear(),
("0"+(e.getMonth()+1)).slice(-2),("0"+e.getDate()).slice(-2)].join("-");d+="MOAT_FEATHER_DEBUG1"+e;var p=0;if(0==d.length)d=p;else{for(e=0;e<d.length;e++)var z=d.charCodeAt(e),p=(p<<5)-p+z,p=p&p;d=m.abs(p)}b="https://px.moatads.com/pixel.gif?"+b+"&na="+d+"&cs=0";var k;try{"undefined"!==typeof omidNative&&("undefined"===typeof Image||Image&&Image._MoatProxyOf)?omidNative.sendUrl(b):(k=new Image(1,1),k.src=b)}catch(g){k=new Image(1,1),k.src=b}return!0};this.an=function(){return h};this.FPAA=function(){return l}}
function v(a,c,f){return a?a&&a.src&&a.src.indexOf&&(-1!==a.src.indexOf("rogerscommunications71796137600/"+c)||-1!==a.src.indexOf("rogerscommunications71796137600%2F"+c))?"undefined"!==typeof a[f]&&!0===a[f]?!1:a[f]=!0:!1:!1}function A(a,c){return!c(a.parent)&&!c(a.top)}function B(){var a=!1;try{a=!!window.top.frames[q.pcode+"_MOAT_IFRAME"]}catch(c){}return a}function w(){if(!c.d.g){c.d.g=!0;var a=t,n="scriptfound"+q.pcode,f=m.floor(m.random()*m.pow(10,10)),h=m.floor(m.random()*m.pow(10,12)),l=a.className||
"-",d=a.getAttribute("src");d||(d="z.moatads.com/rogerscommunications71796137600/moatad.js#");a={sli:"ROGERSCOMMUNICATIONS1"};"string"===typeof q.altKey&&(a[q.altKey]=1);"object"===typeof q.dSA&&(a.dSA=JSON.stringify(q.dSA));a.useSlotIkey=q.useSlotIkey;var b;0>d.indexOf("#")&&0>d.indexOf("?")?b="#":(b=d[d.length-1],b="&"!==b&&"#"!==b?"&":"");var e=[];for(key in a)a.hasOwnProperty(key)&&e.push(key+"="+a[key]);b+=e.join("&");d+=b;l=encodeURIComponent(l)+"@@@"+encodeURIComponent(d);l+="@@@"+encodeURIComponent(JSON.stringify({}));
window.top.postMessage("MSFAPI#1.2#"+h+"#"+n+"#"+f+"#"+l,"*")}}var c={_sdrc:4,_sprg:{104335344:32,26939664:32,4520757593:32}},q={pcode:"rogerscommunicationsheader218955394182"};(function(a){function c(e){if(null==e||a.a.j(e))return!1;var p=e.length;return 1===e.nodeType&&p?!0:"string"===typeof e||a.a.k(e)||0===p||"number"===typeof p&&0<p&&p-1 in e}var f;a.a={};a.a.a={};a.a.b=function(e){return function(){var p=!1;return function(b){try{return e&&e.apply?e.apply(null,arguments):e(b)}catch(c){if(!p){p=
!0;var k=(new r).getTime();this["Moat#ETS"]||(this["Moat#ETS"]=k);this["Moat#EMC"]||(this["Moat#EMC"]=0);var g=36E5<=k-this["Moat#ETS"],d="";try{d=e.toString()}catch(f){d="failed"}d=c.name+" in closure (cb): "+c.message+", stack="+c.stack+", \ncb="+d+"\n";if(!g&&10>this["Moat#EMC"]){this["Moat#EMC"]++;try{var h="undefined"!==typeof omidNative&&("undefined"===typeof Image||Image&&Image._MoatProxyOf),n=h?"":document.referrer,m="undefined"===typeof AD_VIEW_HASH?"ROGERSCOMMUNICATIONS1":AD_VIEW_HASH,
l="undefined"!==typeof a&&a.b&&a.b.a?a.b.a:"",u="https://px.moatads.com/pixel.gif?e=24&d=data%3Adata%3Adata%3Adata&i="+escape(m)+"&ac=1&k="+escape(d)+"&ar="+escape("800ad544c54-clean")+"&iw="+escape("08f52e2")+"&bq="+escape(l)+"&j="+escape(n)+"&cs="+(new r).getTime();if(h)omidNative.sendUrl(u);else{var q=new Image(1,1);q.src=u}}catch(f){}}else if(g){this["Moat#EMC"]=1;this["Moat#ETS"]=k;try{n=(h="undefined"!==typeof omidNative&&("undefined"===typeof Image||Image&&Image._MoatProxyOf))?"":document.referrer,
m="undefined"===typeof AD_VIEW_HASH?"ROGERSCOMMUNICATIONS1":AD_VIEW_HASH,l="undefined"!==typeof a&&a.b&&a.b.a?a.b.a:"",u="https://px.moatads.com/pixel.gif?e=24&d=data%3Adata%3Adata%3Adata&i="+escape(m)+"&ac=1&k="+escape(d)+"&ar="+escape("800ad544c54-clean")+"&iw="+escape("08f52e2")+"&bq="+escape(l)+"&j="+escape(n)+"&cs="+(new r).getTime(),h?omidNative.sendUrl(u):(q=new Image(1,1),q.src=u)}catch(f){}}}}}}()};a.a.d=function(){if(!f){f=new y;var e={e:0};e.d=a.c.a.moatClientLevel1+":"+a.c.a.moatClientLevel2+
":"+a.c.a.moatClientLevel3+":"+a.c.a.moatClientLevel4;e.de=m.floor(m.random()*m.pow(10,12));e.t=(new r).getTime();e.i="MOAT_FEATHER_DEBUG1";e.gw="rogerscommunications71796137600";e.cm="1";e.ac=1;e.f=a.c.b?0:1;e.bq=0;e.ar="800ad544c54-clean";e.iw="08f52e2";a.c.c&&(e.dMoatOQs=a.c.c);a.a.c(e);window[a.a.e()]=f}};a.a.f=function(a){f&&f.sp(a)};a.a.c=function(a){f&&f.__d(a)};a.a.e=function(){return f&&f.an()};a.a.g=function(){return!!f&&f.FPAA()};a.a.h=function(e){var b={};b.fq=e.HEADER_TRACKING?"1":"0";
b.sy=e.HEADER_TRACKING?"1":"0";e.NAMED_IFRAME?(b.gh=1,b.wb=2):(b.gh=0,b.wb=0);a.a.c(b)};a.a.i=function(a){try{var b=a.className,c=a.getAttribute("src");b.split("\n").join(" ");if(-1!==b.indexOf("moatfooter"))return!1;var k=c.split("?"),g=c.split("#");a=!1;1<k.length&&1<g.length&&k[1].length<g[1].length&&(a=!0);if(1==k.length||a)k=g;if(1<k.length){for(var d=k[1],h,g=d,k={},g=g.replace(/&amp;/g,"&").replace(/(^\s+|\s+$)/g,""),f=g.split("&"),g=0;g<f.length;g++){var n=f[g].split("=");if("string"===typeof n[1]){n[0]&&
n[0].match("moatClient")&&(k["rawM"+n[0].slice(1)]=n[1]);a=n;var m,l=n[1],b=l;try{for(c=0;100>c&&(l=decodeURIComponent(l),b!=l)&&!l.match(/^http(s)?\:/);c++)b=l}catch(q){}m=l.replace(/(^\s+|\s+$)/g,"");a[1]=m}else n[1]="";k[n[0]]=n[1]}if(f=k){for(var r in f)f.hasOwnProperty(r)&&r&&r.match("moatClientLevel")&&"string"===typeof f[r]&&(f[r]=f[r].replace(/\:/g,"_").replace(/%3A/gi,"_"));k=f}else k=void 0;h=k;h._originalQueryString=d;return h}return!1}catch(q){return!1}};a.a.j=function(a){return a&&a.document&&
a.location&&a[h+l]&&a[d+b]};a.a.k=function(e){return(e=a.a.a.toString.call(e))&&("[object Array]"===e||"[object Array Iterator]"===e)};a.a.l=c;a.a.forEach=function(a,b,d,k){var g,f=typeof a;if(a)if("function"===f)for(g in a){if("prototype"!=g&&"length"!=g&&"name"!=g&&(k||!a.hasOwnProperty||a.hasOwnProperty(g))&&(f=b.call(d,a[g],g),"boolean"===typeof f&&!f))break}else if("number"===f)for(g=0;g<a&&(f=b.call(d,a,g),"boolean"!==typeof f||f);g++);else if("function"===typeof a.every)a.every(function(a,
e,f){a=b.call(d,a,e);return!("boolean"===typeof a&&!a)});else if(c(a))for(g=0;g<a.length&&(f=b.call(d,a[g],g),"boolean"!==typeof f||f);g++);else for(g in a)if(k||a.hasOwnProperty(g))if(f=b.call(d,a[g],g),"boolean"===typeof f&&!f)break;return a};a.a.m=function(a){return a.parentNode||a.parentElement||!1};a.a.hasChildNodes=function(a){return a&&a.childNodes&&0<a.childNodes.length};a.a.n=function(a,b){return!b(a.parent)&&!b(a.top)};a.a.o=function(){return{HEADER_TRACKING:!1,NAMED_IFRAME:!1}};a.a.p=function(){var b=
{};a._sdrc&&(b.srd=a._sdrc);a._sprg&&(b.srp=a._sprg);return b};var h="ale",l="rt",d="setInte",b="rval"})(c);(function(a){function c(b,e,f){if(!b)return[];var d="boolean"===typeof f?f:!1,k=[b],g=!1;a.a.forEach("number"===typeof e?e:50,function(){if((g=a.a.m(b))&&1==g.nodeType)b=g,k.push(b);else if(d&&g&&9==g.nodeType)if((g=a.e.a(b))&&1==g.nodeType)b=g,k.push(b);else return!1;else return!1});return k}function f(b){if(!b)return!1;if("OBJECT"!==b.nodeName&&"EMBED"!==b.nodeName)return b;b=c(b);var e=!1;
a.a.forEach(b,function(a){if(a&&"OBJECT"!==a.nodeName&&"EMBED"!==a.nodeName)return e=a,!1});return e}function h(b,e){if(!b||!e)return!1;var d=f(e);if(!d)return!1;if(a.a.hasChildNodes(d)){var c=d.childNodes[m.max(0,d.childNodes.length-1)]||null;d.insertBefore(b,c)}else d.appendChild(b);return d}function l(a,e,d){"function"===typeof a.addEventListener?a.addEventListener(e,d):"function"===typeof a.attachEvent&&a.attachEvent("on"+e,d)}function d(b){var e=b.indexOf("#"),d=b.indexOf("?");-1===e&&-1===d?
b+="#":"&"!==b[b.length-1]&&(b+="&");e="fMoatCb="+a.a.e();return b+e}a.d={};a.d.c=function(b){a.d.b&&"function"===typeof window.clearTimeout&&window.clearTimeout(a.d.b);a.d.b=null;try{window.document.documentElement.removeChild(a.d.a),a.d.a=null}catch(e){}a.a.g()&&(a.a.h(b),a.a.f({LOAD:!0}))};a.d.d=function(b,e){var d=!1,f;f=a.a.b(function(c){if(!d&&c&&c.data&&"string"===typeof c.data&&(c=c.data.match(/MSFAPI#1.2#[0-9]+#header_detector#[0-9]+#(.+)/i))){var g=a.a.o();"1"===c[1]?(g.HEADER_TRACKING=
!0,a.d.c(g),b&&b()):(a.d.c(g),e&&e());d=!0;c=window;"function"===typeof c.removeEventListener?c.removeEventListener("message",f):"function"===typeof c.detachEvent&&c.detachEvent("onmessage",f)}});l(window,"message",f)};a.d.e=function(){function b(){if(null===a.d.b)return!1;var b=a.a.o();a.d.c(b);a.d.f()}var e=!1;try{var d=document.createElement("iframe");d.src="https://z.moatads.com/hd09824092/iframe.html#slot=1";d.style.display="none";d.style.width="0px";d.style.height="0px";d.width="0";d.height=
"0";e=h(d,window.document.documentElement);a.d.a=d;if("function"===typeof window.setTimeout){var c=a.a.b(b);a.d.b=window.setTimeout(c,2E3)}}catch(f){}e||b()};a.d.f=function(){if(a.d.g)return!1;a.d.g=!0;a.d.h()};a.d.h=function(){var b=document.createElement("script"),e=t.src.replace("moatad.js","moatcore.js");b.src=d(e);b.onerror=a.a.b(function(a){throw Error("Error loading fallback tag");});a.a.m(t).appendChild(b);return b}})(c);(function(){c.e=c.e||{};c.e.b=function(a,c){};c.e.c=function(a){try{var c=
typeof a.location.toString;if("undefined"===c||"unknown"===c)return!0;var f=typeof a.document;if("undefined"===f||"unknown"===f)return!0;var h=a.innerWidth||a.document.documentElement.clientWidth||a.document.body.clientWidth||0;return"number"!==typeof(a.screenX||a.screenLeft||0)||"number"!==typeof h?!0:!1}catch(l){return!0}}})();var t=function(a){if(!a)return null;var c=a.currentScript;if(v(c,"moatad.js","moatFoundROGERSCOMMUNICATIONS1"))return c;a=a.getElementsByTagName("script");for(c=a.length-
1;-1<c;c--)if(v(a[c],"moatad.js","moatFoundROGERSCOMMUNICATIONS1"))return a[c];return null}(document);if(t){q.dSA=c.a.p();var h=c.a.i(t);c.c={};c.c.a={moatClientLevel1:"ROGERSCOMMUNICATIONS1",moatClientLevel2:h&&(h.moatClientSlicer1||"-"),moatClientLevel3:h&&(h.moatClientSlicer2||"-"),moatClientLevel4:h&&(h.moatClientSlicer3||"-")};c.c.d="ROGERSCOMMUNICATIONS1";c.c.e=h;c.c.c=h&&h._originalQueryString;c.c.b=A(window,c.e.c);h=c.a.o();c.a.d();if(c.c.b){var x=window.top["__moatSlotTagLoaded"+
q.pcode];"function"===typeof x?(h.HEADER_TRACKING=!0,c.d.c(h),q.sli="ROGERSCOMMUNICATIONS1",x(t,q)):(c.d.c(h),c.d.f())}else B()?(h.HEADER_TRACKING=!0,h.NAMED_IFRAME=!0,c.d.c(h),w()):(c.d.d(w,c.d.f),c.d.e())}})(Date,Math)}catch(r){var GLOBAL_VAR=this,ct=(new Date).getTime();GLOBAL_VAR["Moat#ETS"]||(GLOBAL_VAR["Moat#ETS"]=ct);GLOBAL_VAR["Moat#EMC"]||(GLOBAL_VAR["Moat#EMC"]=0);var et=ct-GLOBAL_VAR["Moat#ETS"],hourElapsed=36E5<=et,msg=r.name+" in closure (global): "+r.message+", stack="+r.stack;if(!hourElapsed&&
10>GLOBAL_VAR["Moat#EMC"]){GLOBAL_VAR["Moat#EMC"]++;try{var pixelDomain="px.moatads.com",isDomless="undefined"!==typeof omidNative&&("undefined"===typeof Image||Image&&Image._MoatProxyOf),documentReferrer=isDomless?"":document.referrer,isBeta=!1,viewHash="undefined"===typeof AD_VIEW_HASH?isBeta?"ROGERSCOMMUNICATIONS1_BETA":"ROGERSCOMMUNICATIONS1":AD_VIEW_HASH,tagType="undefined"!==typeof Moat&&Moat.b&&Moat.b.a?Moat.b.a:"",pxSrc="https://"+pixelDomain+"/pixel.gif?e=24&d=data%3Adata%3Adata%3Adata&i="+
escape(viewHash)+"&ac=1&k="+escape(msg)+"&ar="+escape("800ad544c54-clean")+"&iw="+escape("08f52e2")+"&bq="+escape(tagType)+"&j="+escape(documentReferrer)+"&cs="+(new Date).getTime();if(isDomless)omidNative.sendUrl(pxSrc);else{var moat_px=new Image(1,1);moat_px.src=pxSrc}}catch(m){}}else if(hourElapsed){GLOBAL_VAR["Moat#EMC"]=1;GLOBAL_VAR["Moat#ETS"]=ct;try{pixelDomain="px.moatads.com",documentReferrer=(isDomless="undefined"!==typeof omidNative&&("undefined"===typeof Image||Image&&Image._MoatProxyOf))?
"":document.referrer,isBeta=!1,viewHash="undefined"===typeof AD_VIEW_HASH?isBeta?"ROGERSCOMMUNICATIONS1_BETA":"ROGERSCOMMUNICATIONS1":AD_VIEW_HASH,tagType="undefined"!==typeof Moat&&Moat.b&&Moat.b.a?Moat.b.a:"",pxSrc="https://"+pixelDomain+"/pixel.gif?e=24&d=data%3Adata%3Adata%3Adata&i="+escape(viewHash)+"&ac=1&k="+escape(msg)+"&ar="+escape("800ad544c54-clean")+"&iw="+escape("08f52e2")+"&bq="+escape(tagType)+"&j="+escape(documentReferrer)+"&cs="+(new Date).getTime(),isDomless?omidNative.sendUrl(pxSrc):
(moat_px=new Image(1,1),moat_px.src=pxSrc)}catch(m){}}};
